services:
  backend1:
    build: .
    hostname: backend1
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  backend2:
    build: .
    hostname: backend2
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  haproxy:
    image: haproxy:2.8-alpine
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
