services:
  backend1:
    build: .
    image: copirinhago-local:latest
    environment:
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"
  backend2:
    build: .
    image: copirinhago-local:latest
    environment:
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"
  haproxy:
    image: haproxy:2.8-alpine
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
